import Link from 'next/link';
import Image from 'next/image';
import { assetUrl, siteUrl } from '@/lib/site';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { Github } from 'lucide-react';
import { projects } from '@/lib/projects';
import ProjectVisual from '@/components/ProjectVisual';
import { Reveal } from '@/components/Motion';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects.find(p=>p.slug===slug);return {title:`${p?.title??'Project'} | Aadesh Kapadnis`,description:p?.description,alternates:{canonical:`${siteUrl}/projects/${slug}/`},openGraph:{title:p?.title,description:p?.description},twitter:{title:p?.title,description:p?.description}};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();const next=projects[(projects.indexOf(p)+1)%projects.length];const sections=[['Problem',p.problem],['Approach',p.approach],['Data',p.data],['Tools',p.tech.join(' / ')],['Analysis',p.analysis],['Key Insights',p.insights],['Dashboard / Output',p.output],['What I Learned',p.learning]];return <><a className="skip" href="#case-main">Skip to case study</a><header className="nav"><Link href="/" className="wordmark">aadesh<span>AK</span></Link><nav aria-label="Case study navigation"><Link href="/#work">All projects</Link><Link href="/#contact">Let’s talk</Link></nav></header><main id="case-main"><section className="section case-hero"><span className="eyebrow">CASE STUDY / {p.number} — {p.category}</span><Reveal><h1>{p.title}</h1></Reveal><div className="case-intro"><p>{p.description}</p><div className="tech-list">{p.tech.map(t=><span key={t}>{t}</span>)}</div></div><ProjectVisual project={p}/><div className="case-outcome"><span className="eyebrow">PROJECT OUTCOME</span><p>{p.outcome}</p>{p.repo&&<a href={p.repo} className="button outline" target="_blank" rel="noopener noreferrer"><Github size={16}/> VIEW REPOSITORY</a>}</div></section><section className="section case-content"><div className="case-index"><span className="eyebrow">INSIDE THE PROJECT</span><nav aria-label="Case study sections">{sections.map(([title],i)=><a href={`#chapter-${i}`} key={title}>{String(i+1).padStart(2,'0')} / {title}</a>)}</nav></div><div>{sections.map(([title,body],i)=><Reveal key={title}><article id={`chapter-${i}`}><span className="eyebrow">0{i+1}</span><div><h2>{title}</h2><p>{body}</p>{i===6 && p.slug==='e-commerce' && <figure className="real-output"><Image src={assetUrl('/projects/monthly-revenue.png')} alt="Monthly revenue trend from the e-commerce project: revenue in Brazilian reais across September 2016 to September 2018" width={1773} height={873} sizes="(max-width: 600px) 90vw, 60vw"/><figcaption>Actual analysis output · <a href="https://github.com/Shree1194/ecommerce-sales-customer-behavior/blob/main/images/01_monthly_revenue_trend.png" target="_blank" rel="noopener noreferrer">View source chart on GitHub</a></figcaption></figure>}</div></article></Reveal>)}</div></section><section className="section next-project"><span className="eyebrow">NEXT CASE STUDY / {next.number}</span><h2><Link href={`/projects/${next.slug}/`}>{next.short}<span className="blue">.</span></Link></h2><Link className="button outline" href="/#work">BACK TO SELECTED WORK</Link></section></main><footer><div><span className="footer-name">AADESH KAPADNIS</span><span className="eyebrow">DATA ANALYST</span></div><div>© 2026 Aadesh Kapadnis</div><a href="mailto:aadeshkapadnis@gmail.com">Let’s connect</a></footer></>}


