'use client';
import Link from 'next/link';
import Image from 'next/image';
import { assetUrl } from '@/lib/site';
import { ArrowDown, Download, Github, Linkedin, Plus, Minus } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from 'framer-motion';
import { useEffect, useState } from 'react';
import { projects } from '@/lib/projects';
import ProjectVisual from './ProjectVisual';
import { Reveal, Magnetic } from './Motion';
const github='https://github.com/Shree1194';
const linkedin='https://www.linkedin.com/in/aadesh-kapadnis/';
const toolkit=[{name:'Data analysis',note:'Finding the signal in the raw data.',skills:['SQL','Python','Pandas','NumPy','EDA','Data Cleaning','RFM Segmentation']},{name:'Visualization',note:'Making complex findings easy to see.',skills:['Power BI','Excel','Pivot Tables','Power Query','Matplotlib','Seaborn']},{name:'Machine learning',note:'Learning patterns. Evaluating carefully.',skills:['Scikit-learn','Classification','Regression','Feature Engineering','Model Evaluation']},{name:'Tools',note:'The everyday tools behind the work.',skills:['MySQL','Jupyter Notebook','Git','GitHub','VS Code']}];
const workflow=[['Collect','Understand the dataset and the business problem.'],['Clean','Remove inconsistencies and prepare usable data.'],['Analyse','Find patterns, trends, relationships and anomalies.'],['Visualise','Turn findings into dashboards and clear stories.'],['Communicate','Present actionable insights.']];
export default function Portfolio(){const [open,setOpen]=useState<number|null>(0);const [loading,setLoading]=useState(false);const [cursor,setCursor]=useState({x:0,y:0,visible:false});const reduced=useReducedMotion();const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:120,damping:30});
useEffect(()=>{try{if(!sessionStorage.getItem('ak-seen')&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){setLoading(true);sessionStorage.setItem('ak-seen','1');const t=setTimeout(()=>setLoading(false),950);return()=>clearTimeout(t);}}catch{}},[]);
return <><a className="skip" href="#main">Skip to content</a><motion.div className="scroll-progress" style={{scaleX:progress}}/><AnimatePresence>{loading&&<motion.div className="preloader" initial={{opacity:1}} exit={{y:'-100%'}} transition={{duration:.35}}><span>AADESH KAPADNIS</span><span className="eyebrow">DATA ANALYST</span><i/></motion.div>}</AnimatePresence><header className="nav"><a className="wordmark" href="#">aadesh<span>AK</span></a><nav aria-label="Main navigation"><a href="#work">Selected work <sup>04</sup></a><a href="#about">About</a><a href="#contact">Let’s talk <span className="nav-dot"/></a></nav></header><main id="main"><section className="hero"><div className="hero-top"><span className="eyebrow">DATA ANALYST / 2026 GRADUATE</span><span className="eyebrow">NASHIK, INDIA • IST</span></div><div className="hero-stage"><Reveal className="hero-portrait"><Image src={assetUrl('/aadesh-character.png')} alt="Felt-style character portrait of Aadesh Kapadnis, wearing clear glasses and a navy shirt, greeting with open hands" width={1254} height={1254} priority sizes="(max-width: 600px) 92vw, (max-width: 1000px) 48vw, 44vw"/><span className="portrait-caption eyebrow">AADESH KAPADNIS / DATA ANALYST</span></Reveal><Reveal className="hero-headline"><h1>I turn messy data<br/>into <span className="serif">clear</span> <br/>decisions<span className="blue">.</span></h1><span className="hero-signature">A little curiosity.<br/>A lot of possibilities.</span></Reveal></div><div className="hero-bottom"><p>Hi, I’m Aadesh Kapadnis.<br/><span>Electronics & Telecommunication graduate focused on SQL, Python, Excel, Power BI and practical data analysis.</span></p><div className="hero-actions"><Magnetic><a className="button primary" href="#work">VIEW MY WORK</a></Magnetic><Magnetic><a className="button outline" href={assetUrl('/Aadesh-Kapadnis-Resume.pdf')} download="Aadesh-Kapadnis-Resume.pdf"><Download size={15}/> DOWNLOAD RESUME</a></Magnetic></div></div><div className="hero-foot"><a href="#work" className="eyebrow scroll">SCROLL TO EXPLORE <ArrowDown size={16}/></a><div className="mini-bars" aria-hidden="true">{[24,40,29,58,48,70,65,88,76,105,91,120].map((h,i)=><i key={i} style={{height:h}}/>)}</div><div className="hero-social"><a href={github} target="_blank" rel="noopener noreferrer">GitHub</a><a href={linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div></section><div className="ticker" aria-label="Core tools"><span>SQL</span><i>✳</i><span>PYTHON</span><i>✳</i><span>POWER BI</span><i>✳</i><span>EXCEL</span><i>✳</i><span>DATA → DECISIONS</span></div>
<section className="section work-section" id="work"><div className="section-head"><span className="eyebrow">01 / SELECTED WORK</span><p>Practical problems.<br/>Thoughtful solutions.</p></div><Reveal><h2>Less noise.<br/><span className="serif">More insight.</span></h2></Reveal><div className="projects">{projects.map(p=><Reveal key={p.slug} className="project"><div className="project-aside"><span className="project-number">/{p.number}</span><span className="eyebrow">{p.category.split(' / ')[0]}</span></div><div className="project-body"><Link href={`/projects/${p.slug}/`} className="visual-link" aria-label={`Read the ${p.title} case study`} onPointerMove={e=>{if(e.pointerType==='mouse'&&!reduced)setCursor({x:e.clientX,y:e.clientY,visible:true});}} onPointerLeave={()=>setCursor(c=>({...c,visible:false}))} onFocus={()=>setCursor(c=>({...c,visible:false}))}><ProjectVisual project={p}/></Link><div className="project-info"><div><span className="eyebrow muted">{p.category}</span><h3><Link href={`/projects/${p.slug}/`}>{p.short}</Link></h3><div className="tech-list">{p.tech.map(t=><span key={t}>{t}</span>)}</div></div><div><p>{p.description}</p><p className="outcome">{p.outcome}</p><div className="project-links"><Link href={`/projects/${p.slug}/`}>VIEW CASE STUDY</Link>{p.repo&&<a href={p.repo} target="_blank" rel="noopener noreferrer"><Github size={14}/> GITHUB</a>}</div></div></div></div></Reveal>)}</div>{cursor.visible&&<div className="project-cursor" aria-hidden="true" style={{left:cursor.x,top:cursor.y}}>VIEW<br/>STUDY</div>}</section>
<section className="section about-section" id="about"><div className="section-head"><span className="eyebrow">02 / A LITTLE CONTEXT</span><span className="eyebrow">ENGINEERING → ANALYTICS</span></div><Reveal><h2>I’m Aadesh.<br/>An engineer by training.<br/><span className="serif">An analyst by direction.</span></h2></Reveal><div className="about-copy"><span className="about-symbol" aria-hidden="true">✳</span><div><p>I’m a 2026 Electronics & Telecommunication graduate building practical data solutions through analysis, visualization and automation.</p><p className="muted">My project work brings together SQL, Python, Excel and Power BI — from cleaning sales, customer and lending data to exploratory analysis and dashboard development. I’m seeking an entry-level data analyst role focused on reporting and business insights.</p><a className="text-link" href={linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> FIND ME ON LINKEDIN</a></div></div></section>
<section className="section toolkit-section" id="toolkit"><div className="section-head"><span className="eyebrow">03 / MY TOOLKIT</span><p>The right tool.<br/>For the right question.</p></div><Reveal><h2>A practical<br/><span className="serif">set of skills.</span></h2></Reveal><div className="toolkit">{toolkit.map((t,i)=><div className={`skill-row ${open===i?'is-open':''}`} key={t.name} onMouseEnter={()=>setOpen(i)}><button aria-expanded={open===i} aria-controls={`skills-${i}`} onClick={()=>setOpen(open===i?null:i)} className="skill-trigger"><span className="eyebrow">0{i+1}</span><span>{t.name}</span>{open===i?<Minus size={24}/>:<Plus size={24}/>}</button><div id={`skills-${i}`} hidden={open!==i} className="skill-content"><p>{t.note}</p><div className="skill-tags">{t.skills.map(s=><span key={s} tabIndex={0}>{s}</span>)}</div></div></div>)}</div></section>
<section className="section journey"><div className="section-head"><span className="eyebrow">04 / THE FOUNDATION</span><p>Where the learning<br/>became practical.</p></div><div className="journey-grid"><h2>Built on<br/><span className="serif">curiosity.</span></h2><div className="timeline"><Reveal><article><div className="timeline-meta"><span className="eyebrow">EXPERIENCE</span><span>DEC 2024 — FEB 2025</span></div><h3>AI & Data Science Intern</h3><h4>YBI Foundation <span> / Remote</span></h4><p>Built classification and regression models in Python, performing exploratory analysis, data cleaning and feature engineering. Evaluated models with train-test validation and documented findings using Matplotlib and Seaborn visualizations.</p></article></Reveal><Reveal><article><div className="timeline-meta"><span className="eyebrow">EDUCATION</span><span>2022 — 2026</span></div><h3>B.E. Electronics &<br/>Telecommunication</h3><h4>KCT’s Late G. N. Sapkal College of Engineering, Nashik</h4><p>Savitribai Phule Pune University</p><div className="education-stats"><div><strong>6.89<span>/10</span></strong><span>CGPA</span></div><div><strong>7.53<span>/10</span></strong><span>FINAL SEMESTER SGPA</span></div></div><div className="school-stats"><span>HSC <strong>79.50%</strong></span><span>SSC <strong>85.55%</strong></span></div><p className="muted">HSC · Late Vilas Nana Sonawane Jr. College · 2022<br/>SSC · Nampur English School · 2020</p></article></Reveal><Reveal><article><div className="timeline-meta"><span className="eyebrow">CERTIFICATION & COURSEWORK</span><span>2025</span></div><h3>AI & Data Science Internship</h3><h4>YBI Foundation</h4><p>DBMS · Machine Learning · Data Mining · Probability & Statistics · Artificial Intelligence · Data Structures & Algorithms</p></article></Reveal></div></div></section>
<section className="section process-section"><div className="section-head"><span className="eyebrow">05 / HOW I WORK</span><span className="eyebrow">FROM QUESTION TO CLARITY</span></div><Reveal><h2>Good insights start<br/>with <span className="serif">good questions.</span></h2></Reveal><div className="process-grid">{workflow.map(([title,description],i)=><Reveal key={title}><article><span className="eyebrow">0{i+1}</span><div className="process-line"/><h3>{title}</h3><p>{description}</p></article></Reveal>)}</div></section>
<section className="focus-section"><span className="eyebrow">THE NEXT CHAPTER</span><Reveal><p>Currently focused on becoming better at turning <span className="serif">data into decisions.</span></p></Reveal><div className="focus-tags">{['SQL','Python','Power BI','Excel','Data Analytics','Machine Learning'].map(t=><span key={t}>{t}</span>)}</div></section>
<section className="section resume-section" id="resume"><div><span className="eyebrow">THE FULL PICTURE</span><h2>Want the<br/><span className="serif">detailed version?</span></h2></div><div className="resume-action"><a className="button outline" href={assetUrl('/Aadesh-Kapadnis-Resume.pdf')} download="Aadesh-Kapadnis-Resume.pdf"><Download size={16}/> DOWNLOAD RESUME</a><p>PDF · Aadesh Kapadnis</p></div></section>
<section className="section contact-section" id="contact"><div className="section-head"><span className="eyebrow">06 / LET’S CONNECT</span><span className="eyebrow">OPEN TO DATA ANALYST OPPORTUNITIES</span></div><Reveal><h2>Have a dataset,<br/>a problem,<br/>or an <span className="serif">opportunity?</span></h2></Reveal><div className="contact-bottom"><a className="email-link" href="mailto:aadeshkapadnis@gmail.com">aadeshkapadnis@gmail.com</a><Magnetic><a className="button paper-button" href="mailto:aadeshkapadnis@gmail.com">LET’S CONNECT</a></Magnetic></div><div className="contact-social"><a href={github} target="_blank" rel="noopener noreferrer"><Github size={16}/> GitHub</a><a href={linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> LinkedIn</a><a href={assetUrl('/Aadesh-Kapadnis-Resume.pdf')} download="Aadesh-Kapadnis-Resume.pdf"><Download size={16}/> Download Resume</a></div></section></main><footer><div><span className="footer-name">AADESH KAPADNIS</span><span className="eyebrow">DATA ANALYST</span></div><div>Nashik, Maharashtra<br/><span>© 2026 Aadesh Kapadnis</span></div><div className="footer-social"><a href={github}>GitHub</a><a href={linkedin}>LinkedIn</a><a href="mailto:aadeshkapadnis@gmail.com">Email</a></div><a href="#main" className="back-top">BACK TO TOP</a></footer></>}






